# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urzadzenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=30)),
                ('RodzajPlatformy', models.CharField(max_length=30)),
                ('AdresIP', models.CharField(max_length=15)),
                ('Prywatnosc', models.BooleanField()),
                ('Stan', models.BooleanField()),
            ],
        ),
    ]
